package interpolacion;

import java.text.DecimalFormat;


public class frmPrincipaInterpolacion extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipaInterpolacion
     */
    public frmPrincipaInterpolacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtX0 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JLabel();
        txtX2 = new javax.swing.JLabel();
        txtX3 = new javax.swing.JLabel();
        txtFX0 = new javax.swing.JTextField();
        txtFX1 = new javax.swing.JTextField();
        txtFX2 = new javax.swing.JTextField();
        txtFX3 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        txtPolinomio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDif1 = new javax.swing.JTextField();
        txtDif11 = new javax.swing.JTextField();
        txtDif111 = new javax.swing.JTextField();
        txtDif2 = new javax.swing.JTextField();
        txtDif22 = new javax.swing.JTextField();
        txtDif3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Ejercicio Horas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Bacterias");

        txtX0.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtX0.setText("0");

        txtX1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtX1.setText("1");

        txtX2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtX2.setText("2");

        txtX3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtX3.setText("3");

        txtFX0.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtFX0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFX0ActionPerformed(evt);
            }
        });

        txtFX1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtFX2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtFX3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCalcular.setText("Calcular Polinomio");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtPolinomio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Resultado");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("1 Diferencia");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("2 Diferencia");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("3 Diferencia");

        txtDif1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtDif11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtDif111.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDif111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDif111ActionPerformed(evt);
            }
        });

        txtDif2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtDif22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtDif3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel7.setText("NOTA: las diferencias se calculan al dar clic en el boton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtX0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtX1)
                                            .addComponent(txtX2)
                                            .addComponent(txtX3))
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFX3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFX2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFX1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFX0, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnCalcular))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDif1)
                                    .addComponent(txtDif11)
                                    .addComponent(txtDif111))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDif2)
                                    .addComponent(txtDif22))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDif3)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPolinomio, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtX0)
                        .addComponent(txtFX0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDif2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDif3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtX1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDif11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDif22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtX2)
                    .addComponent(txtFX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDif111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtX3)
                    .addComponent(txtFX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolinomio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFX0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFX0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFX0ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        csInterpolacion modelo = new csInterpolacion();
        
        modelo.setFx0(Double.parseDouble(this.txtFX0.getText().trim()));
        modelo.setFx1(Double.parseDouble(this.txtFX1.getText().trim()));
        modelo.setFx2(Double.parseDouble(this.txtFX2.getText().trim()));
        modelo.setFx3(Double.parseDouble(this.txtFX3.getText().trim()));
        modelo.setX0(Double.parseDouble(this.txtX0.getText().trim()));
        modelo.setX1(Double.parseDouble(this.txtX1.getText().trim()));
        modelo.setX2(Double.parseDouble(this.txtX2.getText().trim()));
        modelo.setX3(Double.parseDouble(this.txtX3.getText().trim()));
        
        ctrInterpolacion diferencias = new ctrInterpolacion(modelo);
        DecimalFormat formato = new DecimalFormat("#.#######");
        diferencias.obtener();
        this.txtDif1.setText(String.valueOf(modelo.getDif1()));
        this.txtDif11.setText(String.valueOf(modelo.getDif11()));
        this.txtDif111.setText(String.valueOf(modelo.getDif111()));
        this.txtDif2.setText(String.valueOf(modelo.getDif2()));
        this.txtDif22.setText(String.valueOf(modelo.getDif22()));
        this.txtDif3.setText(String.valueOf(formato.format(modelo.getDif3())));
        
        this.txtPolinomio.setText(diferencias.obtener());
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtDif111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDif111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDif111ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipaInterpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipaInterpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipaInterpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipaInterpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipaInterpolacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDif1;
    private javax.swing.JTextField txtDif11;
    private javax.swing.JTextField txtDif111;
    private javax.swing.JTextField txtDif2;
    private javax.swing.JTextField txtDif22;
    private javax.swing.JTextField txtDif3;
    private javax.swing.JTextField txtFX0;
    private javax.swing.JTextField txtFX1;
    private javax.swing.JTextField txtFX2;
    private javax.swing.JTextField txtFX3;
    private javax.swing.JTextField txtPolinomio;
    private javax.swing.JLabel txtX0;
    private javax.swing.JLabel txtX1;
    private javax.swing.JLabel txtX2;
    private javax.swing.JLabel txtX3;
    // End of variables declaration//GEN-END:variables
}
